# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\PythonCode\OTDR-PyQtObject\ConfigFileEditForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigFileEditForm(object):
    def setupUi(self, ConfigFileEditForm):
        ConfigFileEditForm.setObjectName("ConfigFileEditForm")
        ConfigFileEditForm.resize(936, 627)
        ConfigFileEditForm.setStyleSheet("QWidget#ConfigFileEditForm\n"
"{\n"
"    background-color: rgb(176, 199, 216);    \n"
"}\n"
"\n"
"QTableView,QTextEdit\n"
"{\n"
"    border:3px solid;\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(162, 185, 202, 255), stop:1 rgba(104, 121, 134, 255));    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(185, 212, 231, 255), stop:1 rgba(189, 213, 229, 255));\n"
"    \n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(162, 185, 202, 255), stop:1 rgba(104, 121, 134, 255));\n"
"    \n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(185, 212, 231, 255), stop:1 rgba(189, 213, 229, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigFileEditForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ConfigFileEditForm)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(ConfigFileEditForm)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(ConfigFileEditForm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Save_Button = QtWidgets.QPushButton(ConfigFileEditForm)
        self.Save_Button.setObjectName("Save_Button")
        self.horizontalLayout.addWidget(self.Save_Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(ConfigFileEditForm)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_ConfigFile = QtWidgets.QLineEdit(ConfigFileEditForm)
        self.lineEdit_ConfigFile.setObjectName("lineEdit_ConfigFile")
        self.horizontalLayout_2.addWidget(self.lineEdit_ConfigFile)
        self.loadFile_Button = QtWidgets.QPushButton(ConfigFileEditForm)
        self.loadFile_Button.setObjectName("loadFile_Button")
        self.horizontalLayout_2.addWidget(self.loadFile_Button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(ConfigFileEditForm)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Config_tableView = QtWidgets.QTableView(ConfigFileEditForm)
        self.Config_tableView.setObjectName("Config_tableView")
        self.verticalLayout.addWidget(self.Config_tableView)

        self.retranslateUi(ConfigFileEditForm)
        QtCore.QMetaObject.connectSlotsByName(ConfigFileEditForm)

    def retranslateUi(self, ConfigFileEditForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigFileEditForm.setWindowTitle(_translate("ConfigFileEditForm", "Form"))
        self.label.setText(_translate("ConfigFileEditForm", "转接线缆长度："))
        self.label_3.setText(_translate("ConfigFileEditForm", "米"))
        self.Save_Button.setText(_translate("ConfigFileEditForm", "保存配置"))
        self.label_4.setText(_translate("ConfigFileEditForm", "载入配置文件："))
        self.loadFile_Button.setText(_translate("ConfigFileEditForm", "载入配置..."))
        self.label_2.setText(_translate("ConfigFileEditForm", "编辑测试线缆长度："))
